In [7]:
import pandas as pd
data = pd.read_csv('data.csv', delimiter=',')
data.describe()

,Id,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1094.000000,1350.000000,1350.000000,1350.000000,1350.000000,1307.000000
mean,675.500000,0.060000,3.577895,52.048889,0.257778,356.123363,6438.473492,8.434074,0.080000,0.986667,0.062222,0.737567
std,389.855743,0.237575,84.914699,15.009875,0.751718,1156.603074,7849.754675,5.129287,0.376634,1.008401,0.306555,1.086949
min,1.000000,0.000000,0.000000,22.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,338.250000,0.000000,0.031140,40.000000,0.000000,0.175125,3300.000000,5.000000,0.000000,0.000000,0.000000,0.000000
50%,675.500000,0.000000,0.156891,52.000000,0.000000,0.367049,5222.500000,8.000000,0.000000,1.000000,0.000000,0.000000
75%,1012.750000,0.000000,0.543145,63.000000,0.000000,0.807001,8055.250000,11.000000,0.000000,2.000000,0.000000,1.000000
max,1350.000000,1.000000,2340.000000,97.000000,10.000000,15466.000000,208333.000000,31.000000,5.000000,8.000000,5.000000,8.000000

In [8]:
data.head(10)

,Id,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
5,6,0,0.213179,74,0,0.375607,3500.0,3,0,1,0,1.0
6,7,0,0.305682,57,0,5710.000000,NaN,8,0,3,0,0.0
7,8,0,0.754464,39,0,0.209940,3500.0,8,0,0,0,0.0
8,9,0,0.116951,27,0,46.000000,NaN,2,0,0,0,NaN
9,10,0,0.189169,57,0,0.606291,23684.0,9,0,4,0,2.0